I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 11, in script call
    call D1S1
  File "game/scenes/scenes/D1S3s.rpy", line 72, in script
    jump d1s4
ScriptError: could not find label 'd1s4'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 11, in script call
    call D1S1
  File "game/scenes/scenes/D1S3s.rpy", line 72, in script
    jump d1s4
  File "S:\renpy-8.3.4-sdk\renpy\ast.py", line 1705, in execute
    rv = renpy.game.script.lookup(target)
  File "S:\renpy-8.3.4-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'd1s4'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
Lyceum of Leviathans 1.0
Tue Jan 28 14:12:12 2025
